FROM tomcat:9-jre8
LABEL maintainer="D Prashant Reddy"
EXPOSE 8080
# Remove default Tomcat applications
RUN rm -rf /usr/local/tomcat/webapps/*
# Copy WAR file generated by Maven
COPY target/prashanth.war /usr/local/tomcat/webapps/prashanth.war
